### ISSUE TITLE
It should no longer be necessary to install dotnet-ef.

### ISSUE THREAD

**Issue by asynts** [LionelBergen/codidact-docker#1]
As of pull request codidact/core#52 it should no longer be necessary to install the `dotnet-ef` tool. I don't have the environment to test this in, but it should be possible to remove [these lines][1]:

~~~dockerfile
RUN dotnet tool install --global dotnet-ef
ENV PATH "$PATH:$HOME/.dotnet/tools/"
~~~

  [1]: https://github.com/LionelBergen/codidact-docker/blob/312359cbf2a7569466bd0f33c781f44d5f5ba670/Dockerfile#L16-L17

**Comment by LionelBergen** [comment]
Thanks for noticing that! Code has been updated & tested with the [last commit](https://github.com/LionelBergen/codidact-docker/commit/2d3d2475b22bdcfff17aeee2476de549071af8fe)
